### ISSUE TITLE
how to use this code and make the server available, thanks

### ISSUE THREAD

**Issue by tzz1996** [tomdesair/tus-java-server#1]
hello, i am a student insterested in this project, could you give some steps to run this code correctly? mybe a main(), thank you very much.

**Comment by tomdesair** [comment]
Hi @tzz1996 and @Maxoid,

Thanks (again) for your interest in this project. I've published a released version of this library to Maven Central. You can include it in your project using:

```
<dependency>
  <groupId>me.desair.tus</groupId>
  <artifactId>tus-java-server</artifactId>
  <version>1.0.0-1.0</version>
</dependency>
``` 

An example of how to use this library in combination with Spring Boot and the [JavaScript Uppy](https://uppy.io/) (tus) file upload client can be found here: https://github.com/tomdesair/tus-java-server-spring-demo But in theory you can use this library in many more JVM Web containers like Tomcat, Jetty, WildFly...

The example offers a file upload web interface on URL http://localhost:8080/ and the tus upload API endpoint under http://localhost:8080/api/upload

If you still encounter any issues, feel free to reopen this issue or to submit a new one.

**Comment by Maxoid** [comment]
Congratulate you @tomdesair with the first release! Great job!
