### ISSUE TITLE
Reverse proxy

### ISSUE THREAD

**Issue by zeus19900814** [tomdesair/tus-java-server#24]
Does this work with Nginx reverse proxy? How do I set it up?

John

**Comment by ksvraja** [comment]
This does work with Nginx reverse proxy. You can setup as standard nginx reverse proxy configuration.  

Just make sure the client_max_body_size is set to the maximum file size you are expecting

**Comment by tomdesair** [comment]
An alternative approach is to set `proxy_request_buffering` to `off` so that the upload is immediately streamed to the Tus server and not first buffered in memory by NGINX.

In your `server` block add a `location` directive specific to your upload endpoint like this:

```
        location /api/upload {
            proxy_read_timeout 3600s;
            proxy_request_buffering off;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://127.0.0.1:8080;
        }
```

**Comment by zeus19900814** [comment]
Yes! This works! Thanks!
