### ISSUE TITLE
java17 support

### ISSUE THREAD

**Issue by softboy99** [tomdesair/tus-java-server#48]
### Expected Behaviour

we cannot use in spring boot 3.x without java17 support

### Actual Behaviour
(What faulty behaviour does the implementation have?)

### Steps to reproduce
(Ideally, you specify detailed steps using the curl command.)

**Comment by ghoshrahul** [comment]
@tomdesair , it would be lovely to have this support. I can take a shot at trying to upgrade to java 17 for this.

**Comment by rzhang90** [comment]
We are also considering upgrade to Spring Boot 3.x. Looking forward to Java 17 support.

**Comment by akashp90** [comment]
Any update on this? I'm looking to use this for a project which uses Spring Boot 3.x

**Comment by ghoshrahul** [comment]
The changes are released on maven central
