### ISSUE TITLE
Is there any configuration required to use this in the spring boot server?

### ISSUE THREAD

**Issue by AdityaKBhadragond14** [tomdesair/tus-java-server#58]
Hi, I have a spring boot server do I need to add some configuration to it in order for this to work?

**Comment by AdityaKBhadragond14** [comment]
FYI closing this issue. Solved it.

**Comment by a1psaitz** [comment]
see [https://github.com/tomdesair/tus-java-server-spring-demo](https://github.com/tomdesair/tus-java-server-spring-demo)
