### ISSUE TITLE
[Question] Using tus-java-server with dropwizard

### ISSUE THREAD

**Issue by debraj-manna** [tomdesair/tus-java-server#9]
Is it possible to use this with dropwizard? Is there any documentation or example on how to use this with dropwizard?

**Comment by tomdesair** [comment]
Hi @debraj-manna,

Yes that's possible. I'll create a small demo tus file upload application with Dropwizard. That should give you a good idea of how to use this library in combination with Dropwizard.

I'll update this ticket when it's ready (soon!).

**Comment by debraj-manna** [comment]
Thanks @tomdesair that will be really helpful.

**Comment by tomdesair** [comment]
Hi @debraj-manna 

I've created an example Dropwizard web app here: https://github.com/tomdesair/tus-java-server-dropwizard-demo (I've also linked to it in the main README file now). It offers a basic submission form combined with the [Uppy tus client](https://uppy.io) to do the (resumable) file uploads.

That repository has a [README file](https://github.com/tomdesair/tus-java-server-dropwizard-demo/blob/master/README.md) that contains some pointers to classes where you should start reading the code. I tried to be as complete as possible leveraging the Dropwizard library without adding too much complexity or confusion. However I'm not very familiar with Dropwizard.

Does this answer your question?

**Comment by debraj-manna** [comment]
Thanks @tomdesair
